version: '3.1'
services:
  student_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: student_app
    image: student_app
    restart: always
    ports:
      - "3000:80"